lib/ext/slider.js
See
http://christophercurrie.github.io/technology/2014/03/20/internet-explorer-11-fullscreen-bug.html
http://bugs.jquery.com/ticket/14903
Fixes #757
=> Fix slider for IE11 fullscreen

index.html
- fix jquery version
- mention that jquery is only required for html-based setups
- remove ogg source
=> Update shipped sample page

skin/styl/core/player.styl
Elements which are not interactive should not have pointer cursor.
=> Default cursor elements

index.html
https://github.com/flowplayer/player-commercial/pull/43#issuecomment-104883534
=> Samples: use https to accomodate even paranoid scenarios

lib/common.js, lib/ext/slider.js, lib/ext/ui.js
=> Fix mousemove events for IE8

lib/ext/embed.js
=> Do not pick the whole video object as clip

lib/ext/analytics.js
=> Use clip.title when tracking analytics event

lib/engine/flash.js
=> Don't pick mpegurl source if conf.swfHls is false

lib/as/Flowplayer.as, lib/flowplayer.js
=> Fix jQuery plugin init config precedence

lib/engine/flash.js
As in 5794ba31c187f6ec8bc7acd098866ccabfd3de07 with findDirect.
=> Other instance of strict video tag detection

lib/ext/subtitle.js
=> Respect subtitle `default` property

index.html
For consistency when embedding.
flowplayer/work#1095
=> Use functional skin in shipped sample

lib/engine/html5.js
=> Call player.unload() instead of event trigger

lib/as/NetStreamProvider.as
=> Decode uri before playing

skin/styl/core/timeline.styl
=> Fix touch playahead when border-box is applied

lib/ext/analytics.js, lib/flowplayer.js
=> Implement heartbeat for Google Analytics

lib/as/Flowplayer.as, lib/as/HLSStreamProvider.as, lib/as/NetStreamProvider.as, lib/as/StreamProvider.as, lib/engine/flash.js, lib/flowplayer.js
This will reduce the need of workarounds in javascript code
=> Make Flash object keep its ratio

lib/ext/subtitle.js, lib/ext/ui.js
- 2 problems spotted by @chriswible at https://flowplayer.org/forum/#!/setup:ratiocss-is-not-a-function
=> Misc fixes

lib/engine/html5.js
=> Remove is-live class when duration becomes available

lib/engine/html5.js
...also on video tag based configs
Fixes #883
=> Support giving autoplay on player level config

lib/engine/html5.js
=> Remove old safari hack

lib/flowplayer.js
=> Only parse video tag when there actually is one

lib/common.js, lib/ext/fullscreen.js
=> Copy array before looping through

lib/ext/playlist.js
=> Toggle active class on items outside of container

lib/common.js, lib/ext/subtitle.js
=> Set crossorigin attribute for video tag if needed

lib/ext/embed.js, skin/styl/core/buttons.styl, skin/styl/core/menu.styl
- html5 compliant iframe embedding
- future proof retina media queries
=> css modernize

lib/as/Flowplayer.as, lib/engine/flash.js
=> Escape video url on on initialize

lib/ext/events.js
Fixes #928
See:
http://stackoverflow.com/questions/23349191/event-preventdefault-is-not-working-in-ie-11-for-custom-events
=> Custom preventDefault implementation

lib/ext/cuepoint.js
=> Don't disable cuepoints for prevented event

lib/engine/flash.js, lib/engine/html5.js, lib/flowplayer.js
=> Don't convert video.src to full url if rtmp

lib/as/HLSStreamProvider.as
=> Delay ready event until buffered

lib/common.js, lib/engine/html5.js, lib/ext/subtitle.js
=> Remove track elements from cached video tag

lib/ext/cuepoint.js
=> fixed #969 bug when using objects to define cuepoints

lib/as/NetStreamProvider.as
=> Pause after seek if in paused state

lib/flowplayer.js
=> Async trigger error when giving up finding engine

lib/engine/html5.js, lib/flowplayer.js
=> Fix buffer handling

lib/ext/playlist.js, lib/flowplayer.js
Use it in the playlist extension
Fixes #1063
=> Introduce `beforeseek` event

lib/engine/html5.js, lib/ext/support.js
=> Inline playback support for iPhone/iOS10

lib/flowplayer.js
Also checks specifically for mute.
Fixes #1073
=> Let other ready handlers run before setting volume

lib/as/Flowplayer.as, lib/as/HLSStreamProvider.as, lib/engine/flash.js, lib/engine/html5.js
=> Enable support for ID3 events

lib/ext/playlist.js
=> Remove beforeresume handler while seeking

skin/sass/skin.sass
=> Never show built-in iOS controls

lib/as/HLSStreamProvider.as, lib/engine/flash.js, lib/engine/html5.js, lib/ext/ui.js, lib/flowplayer.js, skin/sass/state.sass
Works only in the html5 engine for now (Desktop Safari)
=> DVR support

lib/ext/events.js, test/unit/events.js
=> Don't call splice within a loop

lib/ext/ui.js, skin/sass/skin.sass
(Some engines might send a fake progress event in paused state)
=> Remove poster on resume instead of progress

lib/ext/ui.js, skin/sass/skin.sass
=> Style speed flash indicator

skin/sass/skin.sass
=> Center timeline on fp-minimal on IE11

lib/ext/mobile.js
=> Don't use native_fullscreen when real fullscreen is supported

lib/as/HLSStreamProvider.as, lib/engine/flash.js, lib/engine/html5.js, lib/ext/embed.js, lib/ext/support.js, lib/ext/ui.js, lib/flowplayer.js, skin/sass/state.sass, test/dvr.html
=> DVR live status indicator

lib/as/HLSStreamProvider.as
=> Read duration etc from the actual current level

lib/engine/html5.js, package.json
=> Preload video for JS-created first frame setups

lib/ext/playlist.js
=> Handle playlist additions while playing last clip

lib/common.js
Solves 2. here:
https://github.com/flowplayer/player-commercial/issues/73#issuecomment-314771418
=> common.createElement: Win7 IE compatibility

lib/ext/ui.js
=> Fix for "Cannot assign to read only property 'message' of object '#<MediaError>'"

lib/engine/html5.js
=> Fix safari HLS dimesion bug

lib/ext/support.js
=> No support of firstframe and mutedAutoplay on any iOS < 10 device
