flowplayer/flowplayer

lib/engine/flash.js

- flash hls itself handles video and therefore object resizing
- webkit ready callback obsolete because there's no flash re-init anymore

Flash callback redux

---

lib/engine/html5.js

For broken android devices that do not report HLS duration try to make
them believe it's a live setup and trigger ready event

Try working around #812

---

lib/common.js
lib/engine/html5.js

If crossorigin attribute set and no cross-domain subtitle tracks loaded
the player vill error at least on chrome
Fixes #826

Remove crossorigin attribute from videotag

---

lib/ext/playlist.js

`conf.query` starting with the `#` sign will be treated as being outside
of the container
Fixes #443

Allow playlist items outside of the container

---

lib/ext/ui.js

When there is a horizontal scrollbar in the browser and you scroll to the right, the context menu is not created next to the mouse cursor - it is placed to the right. It needs to take into account the horizontal scroll amount.

Fix incorrect horizontal position of the context menu

---

lib/ext/ui.js

is-seeking class has the same visual effect as is-loading, so remove it
as well.

Do not show loading animation when erroring out during seek

---

lib/engine/html5.js

Needed at least for Mac OS desktop Safari.
The greediness of the condition manifests itself because of
8dd719a64f03b09573eeed0a68876ae2b14d0bdd for Android.

Detect live clip properly in ready handle (#898)

---

lib/ext/cuepoint.js

The return false hack does not work in the version 6 layout, and is not
needed. The mousedown event just must prevented from propagating.

Seek to generated cuepoint, not timeline position (#957)

---

lib/ext/playlist.js

`startIndex` tells the player to start not at the first item of a playlist, but rather at an arbitrary index. 
This controls which clip is cued up first (either for immediate playback in the case of autoplay, or to be played first when the player is clicked).
Configuring a starting index rather than explicitly calling `play(index)` works better in non-autoplay scenarios, and avoids an extraneous "load" event for the 0th item.
Closes #973

Add a 'playlist_index' option to specify which playlist item to start on

---

skin/styl/core/player.styl

Place all off-page elements on top, not on left. left otherwise takes
priority and extends the page by 9999em to the left.

Prevent horizontal scrollbar with ltr player in rtl page (#1005)

---

skin/styl/core/state.styl

Slightly darker color than for timeline to preserve a contrast to the
volume slider background.

Grey out volume level in disabled state (#1017)

---

lib/ext/embed.js

Users may have worked around #997, so do not break their setups, and
it's flexible at low cost.

Make iframe embed dimensions accept both numbers and strings (#997)

---

lib/engine/html5.js

Empty video tag src attribute before removal.

html5 unload: prevent VOD files from continuing to buffer (#1025)

---

lib/ext/ui.js

- correct off by one (time + remaining resulting in (duration - 1)) by
basing remaining seconds on Math.ceil(seconds) instead of Math.floor
- ensure that seconds to format are never negative
- replace Infinity with 0

Fix time format glitches (#1036)

---

lib/engine/html5.js
lib/ext/ui.js

This is not only a display problem, the player may stall with some live
streams otherwise; so set duration to 0 on engine level if it is >=
Number.MAX_VALUE.
See:
https://github.com/flowplayer/flowplayer-mpegdash/commit/0392ad27fa56528b57e2e67222e9da620ca275b4

Ensure video.duration < Number.MAX_VALUE (#1036)

---

lib/ext/embed.js
lib/ext/ui.js
skin/styl/core/buttons.styl
skin/styl/core/embed.styl
skin/styl/minimalist.styl

Wraps all (upper-right corner) buttons in a container.
It will be the only absolutely positioned element in the upper-right
corner.
All buttons inside the container will flow freely. This will allow us to
be more flexible in adding / removing buttons without gaps etc.

Wrap buttons in a container

---

lib/ext/embed.js

Arguably it would make sense to require both width and height configured
for a static layout. Especially height only will almost certainly lead
to strange results. Assume users know what they are doing when they
configure a dimension.

Make iframe embed code responsive if width and height not given (#804)

---

skin/styl/core/player.styl

Due to offset calculation problems in webkit (ank blink) based browsers
it becomes impossible to support CSS zoom for the player element.
Closes #1056

Enforce zoom: 1 for Flowplayer root element

---

lib/ext/embed.js

fp7 does not feature:
- slim timeline (4px)
- fixed-controls modifier (controlbar height below player area)
So bottom padding of container wrapper is never needed.

embed: omit bottom padding of container wrapper

---

lib/engine/html5.js
lib/ext/support.js
test/dvr.html

* Don't use autoplay where it can't be used
* Don't use preload where it does not make any sense
* Only call `load()` and `play()` on video tag when really needed
Fixes #1104

Simplify HTML5 engine load

---

lib/ext/ui/bar-slider.js

Otherwise
flowplayer().sliders.volume.slide(0, true)
will throw:
Uncaught TypeError: Failed to set the 'volume' property on
'HTMLMediaElement': The provided double value is non-finite.
See:
https://flowplayer.org/forum/#!/setup:nan-exception-on-setting-vo

bar-slider: bean.fire third argument must be array

---

lib/ext/ui.js

With the prominent Flowplayer 7 speed flash, the initial "1x" in Firefox
is very annoying.
But with Flowplayer 7 and in recent Firefox, not firing speed flash when
video.time is 0 seems to avoid most cases.
refs #385
supersedes https://github.com/flowplayer/flowplayer/pull/541
See also:
https://flowplayer.org/forum/#!/setup:firefox-showing-1x

Do not indicate speed rate change when playback starts

---

lib/flowplayer.js

In part this also solves #844: poster functionality works, instead of
video not loading.

native hls live: do not seek to 0 on stop (#1189)

---

lib/as/NetStreamProvider.as

When ffmpeg stops and then restarts, the video is playing correctly but the toolbar remains visible on the screen and can't be removed.
The problem is the same in the 6.0.5 version but with the Play button on the middle of the screen.
See forum entry: 'Play button remains on the screen after ffmpeg restarts'
And support ticket: [Ticket#2017071381000762] ID 270071. Following up from forum post thread 'Play button remains on the screen after ffmpeg restarts.

ffmpeg restart problem. The toolbar remains visible after ffmpeg restarts

---

lib/ext/ui.js
skin/sass/state.sass

The timestamp is especially informative for DVR as it can show the
current or desired position inside the DVR window. So show it.
The CSS hiding of the timestamp for live (not dvr) can be omitted. It
was redundant anyway because is-live hides the timeline, and therefore
one cannot mousemove over it.

dvr: display timestamp (#1137)

---

lib/ext/mobile.js
lib/ext/support.js
lib/flowplayer.js

- support.android now applies to all clients on Android, including
Firefox; support.android.firefox now returns true in Firefox
- Samsung stock browser now properly detected
- Android Firefox does not support firstframe setups, but mutedAutoplay:
do not enforce splash when autoplay is given, so it can autoplay,
while enforcing splash for firstframe
- Samsung stock browser supports firstframe, but not mutedAutoplay:
make it behave exactly like iOS < 10 by pretending it does not support
firstframe - this is above all for consistency: so far we treat
support.autoplay as synonym of support.firstframe
TODO: Android Opera
Is currently treated like Android Chrome except in one place. May need
further special casing.

Revisit Android client detection (#1249)

---

lib/ext/subtitles/parser.js

Allows the following to pass:
- while the hours field must have at least 2 digits, some real world vtt
have only one
- hours > 99
For simplicity of pattern also allows single digit minutes, while still
requiring the field.

Make first field of subtitle TIMECODE_RE less strict (#1237)

---

lib/ext/share.js

when there is a non-ASCII (for example utf-8) characters in configs btoa has an error. with escaping them this problem will be fixed

Fix bug for non-ASCII characters in config

---

lib/flowplayer.js

Fail over to 0 otherwise.
Avoids type error in desktop Safari with empty cache in many autoplay
scenarios.

Ensure buffered property has length (#1325)

---

lib/as/NetStreamProvider.as
lib/engine/flash.js

We've seen that when playing live RTMP streams we can end up where the latency keeps growing and never recovers.
This is especially true using a small value for bufferTime to act as a jitter buffer since a non-zero bufferTime sets the NetStream in non-live mode which has quite different behaviour to live. However we've also seen this in live mode when due to network conditions you can end up with a large latency which never recovers.
Having the option to set bufferTimeMax allows a latency limit to be set. Once this limit has been crossed the flash will catch up by playing faster until the original bufferTime value has been reached.
https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/net/NetStream.html#bufferTimeMax
It would be better for our use case if there was an …

added support for bufferTimeMax

---

lib/engine/hlsjs.js

Hls.Events.ERROR should handle events there manifest can not be parsed like then m3u8 file can not be found. Those events occurs before Hls.Events.MANIFEST_PARSED has been triggered.

moved event ERROR outside event MANIFEST_PARSED

---

lib/ext/support.js

Android 9 is now shipping to Pixel phones, and the Flowplayer plugin crashes on load on this version.
This is due to the user agent regex used to parse the Android version failing to match, and a `null` match set being dereferenced.
The regex assumes that both major and minor version numbers are present, e.g. `Android 8.1`, whereas the UA string for Android 9 just contains `Android 9`.
This change makes the minor version portion of the string optional in the match.
Also, the regex assumes a single digit for each component of the version number, meaning that it will also break for Android 10 user agent strings, when they appear.
This change makes the regex accept multi-digit version numbers as well.
Fixes #1404.

Make Android UA detection robust to new versions
